// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteEF_LowPower.Data;

#nullable disable

namespace SQLiteEF_LowPower.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SQLiteEF_LowPower.Models.ChooseComponentsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommunicationModules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerManagementComponents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sensors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stm32Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChooseComponent");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.ComponentSelectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectorsInterfaces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LowPowerComponents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentSelection");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.DefineRequirementsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FunctionalRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DefineRequirements");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.DesignSchematicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockDiagram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircuitSchematics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerSupplyCircuits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DesignSchematic");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.DocumentationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesignDocumentation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareDocumentation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documentation");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.FinalPrototypeFabricationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FabricationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDesignFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinalPrototypeFabrication");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.FirmwareDevelopmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicFunctionalityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationProtocols")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerManagementFeatures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FirmwareDevelopment");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.FirmwareFinalizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalFirmware")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FirmwareFinalization");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.IterateDesignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestingResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IterateDesign");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.PcbLayoutModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentPlacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolationStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerOptimization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerSignalRouting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PcbLayout");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.PcbPrototypeFabricationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesignFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PcbPrototypeFabrication");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.PowerManagementDesignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PowerSavingModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerSwitchingCircuits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PowerManagementDesign");
                });

            modelBuilder.Entity("SQLiteEF_LowPower.Models.SafetyRedundancyDesignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedundancyDesign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyFeatures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SafetyRedundancyDesign");
                });
#pragma warning restore 612, 618
        }
    }
}
